name-template: 'Release v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR'
exclude-labels:
  - 'hotfix'
filter-by-commitsh: true
categories:
  - title: 'API'
    label: 'api'
  - title: 'JSF'
    label: 'jsf'
  - title: 'Agendamentos'
    label: 'agendamento'
  - title: 'Criar Conta'
    label: 'criarconta'
  - title: 'Controle Versão'
    label: 'controleversao'
  - title: 'Cobrança Alerta'
    label: 'cobrancaalerta'
  - title: 'Cobrança Email'
    label: 'cobrancaemail'
  - title: 'Email Enviar'
    label: 'emailenviar'
  - title: 'Integração Asaas'
    label: 'integracaoasaas'
  - title: 'Integração Importar'
    label: 'integracaoimportar'
  - title: 'Integração OList'
    label: 'integracaoolist'
  - title: 'Integração PJ Bank'
    label: 'integracaopjbank'
  - title: 'JOBs'
    label: 'jobs'
  - title: 'Modelo Spring'
    label: 'modelospring'
  - title: 'NFe API'
    label: 'nfeapi'
  - title: 'NFe Integração'
    label: 'nfeintegracao'
  - title: 'Relatórios Jasper'
    label: 'relatoriosjasper'
  - title: 'SPED'
    label: 'sped'
  - title: 'Nova Arquitetura'
    label: 'novaarquitetura'
  - title: 'DevOps'
    label: 'devops'
  - title: 'Dependências'
    label: 'dependencies'
  - title: 'Documentação'
    label: 'documentation'
  - title: 'Chamados'
    label: 'chamado'
  - title: 'Merge to Release'
    label: 'merge.to.release'
  - title: 'Merge to Master'
    label: 'merge.to.master'
  - title: 'Produto'
    label: 'produto'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'major'
no-changes-template: 'Em desenvolvimento ![loading](https://www.asaas.com/assets/loading.gif)'
change-template: '#$NUMBER | $TITLE @$AUTHOR'
template: |
  ## Alterações
  $CHANGES
