ARG mavenImage
ARG mavenImageVersion
FROM ${mavenImage}:${mavenImageVersion} as builder
ARG nameSpace
ARG DskipTests
WORKDIR /app
COPY . /app

RUN mvn package -f pom-base.xml -Dversao=$nameSpace $DskipTests

